name 'f5_configurator_cookbook'
maintainer 'Austin Heiman'
maintainer_email 'atheimanksu@gmail.com'
license 'all_rights'
description 'Installs/Configures f5_configurator_cookbook'
long_description 'Installs/Configures f5_configurator_cookbook'
version '0.1.0'
